In [16]:
import pandas as pd
import numpy as np
import sqlalchemy as db         #creates de connection with db
from getpass import getpass     #needed for the encripted password
import pymysql

In [4]:
pkdb = pd.read_csv("pokemon.csv")
pkdb

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [17]:
password = getpass("Mysql Password: ")

Mysql Password: ········

In [19]:
#the connectionData var is always like that
dbName = "pokemon"
connectionData = f"mysql+pymysql://root:{password}@localhost/{dbName}"

In [20]:
#necessary from now on to do anything, create tables, make queries, modify columns, etc
engine = db.create_engine(connectionData)

In [23]:
#creating table in db "pkdb"
pkdb.to_sql('poke_details', con = engine, if_exists = 'append', chunksize = 1000)

In [26]:
query1 = pd.read_sql_query("""
select * from poke_details
where Legendary = 1;
""", engine)
query1

,index,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,156,144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,1
1,157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,1
2,158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,1
3,162,150,Mewtwo,Psychic,None,680,106,110,90,154,90,130,1,1
4,163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,1
61,796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,1
62,797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,1
63,798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,1
64,799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,1